// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title AgreementRegistry
 * @notice Member 1's module — this is the foundation that every other module
 *         (Funding, MilestonePayout, RefundDispute) inherits from.
 *
 * What this contract is responsible for:
 *   1. Registering users as either a Shipper or a Carrier.
 *   2. Storing the core `Agreement` data (who's involved, how much, deadline, status).
 *   3. Providing access-control modifiers (onlyShipper, onlyCarrier, onlyParticipant...)
 *      that other modules re-use so nobody has to repeat this logic.
 *
 * IMPORTANT for teammates:
 *   - Do NOT edit this file. If you need something added here (e.g. a new field
 *     on Agreement), ask Member 1 first — every module inherits this struct.
 *   - Your own contract should be written as:
 *         abstract contract YourModule is AgreementRegistry { ... }
 *     This gives you direct access to `agreements[id]`, `userRole[addr]`,
 *     and all the modifiers below, with zero extra wiring.
 */
abstract contract AgreementRegistry {
    // ---------------------------------------------------------------------
    // Enums
    // ---------------------------------------------------------------------

    /// @notice A registered user is either a Shipper (pays) or a Carrier (delivers).
    enum Role {
        None, // default value for anyone who hasn't registered yet
        Shipper,
        Carrier
    }

    /// @notice Lifecycle states an Agreement can be in.
    /// Other modules are expected to move an agreement forward through these
    /// states using the internal `_setStatus` helper below.
    enum AgreementStatus {
        Created, // agreement exists, but Shipper hasn't funded it yet
        Funded, // Shipper has locked the full payload value in escrow
        InProgress, // at least one milestone has been verified/paid
        Completed, // all milestones verified and paid out
        Refunded, // Carrier missed the deadline, funds returned to Shipper
        Disputed // reserved for the optional arbitration extension
    }

    // ---------------------------------------------------------------------
    // Data structures
    // ---------------------------------------------------------------------

    struct Agreement {
        uint256 id;
        address shipper;
        address carrier;
        uint256 payloadValue; // total amount (in wei) the Shipper agreed to pay
        uint256 milestoneCount; // how many milestones this agreement is split into
        uint256 deadline; // unix timestamp; after this, Carrier is considered late
        uint256 createdAt;
        AgreementStatus status;
    }

    // ---------------------------------------------------------------------
    // Storage
    // ---------------------------------------------------------------------

    /// @notice role a wallet address has registered as.
    mapping(address => Role) public userRole;

    /// @notice all agreements, keyed by their auto-incrementing id.
    mapping(uint256 => Agreement) public agreements;

    /// @notice total number of agreements ever created. Also used to generate new ids.
    uint256 public agreementCount;

    // ---------------------------------------------------------------------
    // Events
    // ---------------------------------------------------------------------

    event UserRegistered(address indexed user, Role role);

    event AgreementCreated(
        uint256 indexed agreementId,
        address indexed shipper,
        address indexed carrier,
        uint256 payloadValue,
        uint256 milestoneCount,
        uint256 deadline
    );

    event AgreementStatusChanged(
        uint256 indexed agreementId,
        AgreementStatus oldStatus,
        AgreementStatus newStatus
    );

    // ---------------------------------------------------------------------
    // Modifiers (shared access control for every module)
    // ---------------------------------------------------------------------

    modifier onlyRole(Role requiredRole) {
        require(userRole[msg.sender] == requiredRole, "AgreementRegistry: wrong role");
        _;
    }

    modifier onlyShipper() {
        require(userRole[msg.sender] == Role.Shipper, "AgreementRegistry: caller is not a Shipper");
        _;
    }

    modifier onlyCarrier() {
        require(userRole[msg.sender] == Role.Carrier, "AgreementRegistry: caller is not a Carrier");
        _;
    }

    /// @dev Restricts a function to only the Shipper or Carrier who are part of this specific agreement.
    modifier onlyParticipant(uint256 agreementId) {
        Agreement storage a = agreements[agreementId];
        require(
            msg.sender == a.shipper || msg.sender == a.carrier,
            "AgreementRegistry: not a participant of this agreement"
        );
        _;
    }

    /// @dev Makes sure the agreement id actually exists before continuing.
    modifier agreementExists(uint256 agreementId) {
        require(agreementId > 0 && agreementId <= agreementCount, "AgreementRegistry: agreement does not exist");
        _;
    }

    /// @dev Makes sure the agreement is currently in the status the calling function expects.
    /// Example: Funding should only work while status == Created.
    modifier atStatus(uint256 agreementId, AgreementStatus expected) {
        require(agreements[agreementId].status == expected, "AgreementRegistry: invalid agreement status");
        _;
    }

    // ---------------------------------------------------------------------
    // Core functions (Member 1's required deliverables)
    // ---------------------------------------------------------------------

    /**
     * @notice Register the caller's wallet as either a Shipper or a Carrier.
     * @dev Each wallet can only register once. Role cannot be changed afterwards
     *      to keep things simple and prevent role-switching abuse mid-agreement.
     */
    function registerUser(Role role) external {
        require(role == Role.Shipper || role == Role.Carrier, "AgreementRegistry: invalid role");
        require(userRole[msg.sender] == Role.None, "AgreementRegistry: already registered");

        userRole[msg.sender] = role;
        emit UserRegistered(msg.sender, role);
    }

    /**
     * @notice Shipper creates a new logistics agreement with a chosen Carrier.
     * @param carrier address of the Carrier this agreement is for (must already be registered as Carrier).
     * @param payloadValue total amount (in wei) the Shipper intends to pay across all milestones.
     * @param milestoneCount how many milestones this agreement will be split into (must be at least 1).
     * @param durationInDays how many days from now the Carrier has to complete the job.
     * @return agreementId the id of the newly created agreement.
     *
     * Note: this only creates the agreement record with status = Created.
     * Actually locking the ETH happens in the Funding module's fundAgreement().
     */
    function createAgreement(
        address carrier,
        uint256 payloadValue,
        uint256 milestoneCount,
        uint256 durationInDays
    ) external onlyShipper returns (uint256 agreementId) {
        require(userRole[carrier] == Role.Carrier, "AgreementRegistry: target address is not a registered Carrier");
        require(payloadValue > 0, "AgreementRegistry: payload value must be greater than zero");
        require(milestoneCount > 0, "AgreementRegistry: must have at least one milestone");
        require(durationInDays > 0, "AgreementRegistry: duration must be greater than zero");

        agreementCount += 1;
        agreementId = agreementCount;

        uint256 deadline = block.timestamp + (durationInDays * 1 days);

        agreements[agreementId] = Agreement({
            id: agreementId,
            shipper: msg.sender,
            carrier: carrier,
            payloadValue: payloadValue,
            milestoneCount: milestoneCount,
            deadline: deadline,
            createdAt: block.timestamp,
            status: AgreementStatus.Created
        });

        emit AgreementCreated(agreementId, msg.sender, carrier, payloadValue, milestoneCount, deadline);
    }

    // ---------------------------------------------------------------------
    // Internal helper for other modules
    // ---------------------------------------------------------------------

    /**
     * @dev Other modules (Funding, MilestonePayout, RefundDispute) call this
     *      to move an agreement forward in its lifecycle. Keeping this in one
     *      place means the status-change event is always emitted consistently,
     *      no matter which module triggered the change.
     */
    function _setStatus(uint256 agreementId, AgreementStatus newStatus) internal {
        AgreementStatus oldStatus = agreements[agreementId].status;
        agreements[agreementId].status = newStatus;
        emit AgreementStatusChanged(agreementId, oldStatus, newStatus);
    }

    // ---------------------------------------------------------------------
    // View functions (read-only, free to call)
    // ---------------------------------------------------------------------

    function getAgreement(uint256 agreementId)
        external
        view
        agreementExists(agreementId)
        returns (Agreement memory)
    {
        return agreements[agreementId];
    }

    function getUserRole(address user) external view returns (Role) {
        return userRole[user];
    }

    function isParticipant(uint256 agreementId, address user) external view returns (bool) {
        Agreement storage a = agreements[agreementId];
        return (user == a.shipper || user == a.carrier);
    }
}
